export default function handler(request, response) {
  response.status(200).json({
    response: [
      {
        id: 1,
        criticidad: "Muy Alta",
        equipo: "Jon",
        fabricante: "Forel",
        status: "Activo",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 2,
        criticidad: "Muy Alta",
        equipo: "Cersei",
        fabricante: "Forel",
        status: "Parado",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 3,
        criticidad: "Alta",
        equipo: "Jaime",
        fabricante: "Forel",
        status: "Parado",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 4,
        criticidad: "Media",
        equipo: "Arya",
        fabricante: "Forel",
        status: "Activo",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 5,
        criticidad: "Baja",
        equipo: "Daenerys",
        fabricante:
          "Forelcrfev rewvetrvervtyv bvervtyvtrvtrbvr btyryunbtyuntyiuniutn iuyntuinyubinntu",
        status: "Activo",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 6,
        criticidad: "Muy Alta",
        equipo: null,
        fabricante: "Forel",
        status: "Parado",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 7,
        criticidad: "Media",
        equipo: "Ferrara",
        fabricante: "Forel",
        status: "Activo",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 8,
        criticidad: "Alta",
        equipo: "Rossini",
        fabricante: "Forel",
        status: "Parado",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        actividades: 4,
        ultimaActividad: new Date(),
      },
      {
        id: 9,
        criticidad: "Baja",
        equipo: "Harvey",
        fabricante: "Forel",
        status: "Activo",
        fechaCreacion: new Date(),
        ultimaModificacion: new Date(),
        ultimaActividad: new Date(),
      },
    ],
  });
}